apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  labels:
    app: sso
  name: test-user
spec:
  realmSelector:
    matchLabels:
      app: openshift
  user:
    email: dshirley-test@redhat.com
    credentials:
      - type: password
        value: p
    emailVerified: true
    enabled: true
    firstName: test
    lastName: test
    realmRoles:
    - realm-management
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
    username: test
