apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "3"

resources:
  - stackrox-secret-pipelinerun.yaml
