apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Shared CI/CD tools.
    openshift.io/display-name: Shared CI/CD
  labels:
    argocd.argoproj.io/managed-by: devteam1-gitops
  name: cicd-tools
