apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: gitbucket-import-repos-build
  labels:
    app: gitbucket
spec:
  source:
    type: Git
    git:
      uri: https://github.com/davecore82/gitbucket.git
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: import-repos:latest
  triggers:
    - type: ConfigChange      