apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitbucket
    app.kubernetes.io/component: gitbucket
    app.kubernetes.io/instance: gitbucket
  name: gitbucket
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: gitbucket
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: gitbucket
    spec:
      initContainers:
      - name: copy-db
        image: registry.redhat.io/ubi8/openjdk-8
        command: ['sh', '-c', '
          curl -L -o h2.jar https://github.com/h2database/h2database/releases/download/version-2.1.214/h2-2.1.214.jar

          java -cp h2.jar org.h2.tools.Script -url jdbc:h2:/data/gitbucket/fred;AUTO_SERVER=TRUE; -user sa -script test.zip -options compression zip

          ls -la
          
            #-user ${gitbucket.db.user} -password ${gitbucket.db.password} \
          #java -cp /home/jboss/h2.jar org.h2.tools.Script -url "jdbc:h2:file:./foo" -user sa -password ""
          #java -cp /home/jboss/h2.jar org.h2.tools.RunScript -url "jdbc:h2:file:./vocablesDb" -user username -password pazzword -script query.sql -showResults

          ls $GITBUCKET_HOME -la

          java -version']
        env:
          - name: GITBUCKET_HOME
            valueFrom:
              configMapKeyRef:
                name: gitbucket-config
                key: gitbucket.home
          - name: gitbucket.db.password
            valueFrom:
              secretKeyRef:
                name: gitbucket-db
                key: gitbucket.db.password
          - name: gitbucket.db.user
            valueFrom:
              secretKeyRef:
                name: gitbucket-db
                key: gitbucket.db.user
        volumeMounts:
        - mountPath: /data/gitbucket
          name: gitbucket-data
      containers:
      - image: quay.io/rh_ee_dshirley/gitbucket:4.38.4
        imagePullPolicy: IfNotPresent
        name: gitbucket
        env:
          - name: gitbucket.db.password
            valueFrom:
              secretKeyRef:
                name: gitbucket-db
                key: gitbucket.db.password
          - name: gitbucket.db.user
            valueFrom:
              secretKeyRef:
                name: gitbucket-db
                key: gitbucket.db.user
          - name: GITBUCKET_DB_URL
            valueFrom:
              secretKeyRef:
                name: gitbucket-db
                key: gitbucket.db.url
          - name: GITBUCKET_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: gitbucket-config
                key: gitbucket.base_url
          - name: GITBUCKET_HOME
            valueFrom:
              configMapKeyRef:
                name: gitbucket-config
                key: gitbucket.home
          - name: GITBUCKET_PORT
            valueFrom:
              configMapKeyRef:
                name: gitbucket-config
                key: GITBUCKET_PORT
        ports:
        - containerPort: 29418
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/gitbucket
          name: gitbucket-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: gitbucket
      serviceAccountName: gitbucket
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gitbucket-data
          persistentVolumeClaim:
            claimName: gitbucket-data
