apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitbucket
    app.kubernetes.io/component: gitbucket
    app.kubernetes.io/instance: gitbucket
  name: gitbucket
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: gitbucket
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: gitbucket
    spec:
      initContainers:
      - name: copy-db
        image: registry.access.redhat.com/ubi8/ubi:latest
        command: ['sh', '-c', 
          'curl google.ca > some-file.txt; cp some-file.txt $GITBUCKET_HOME']
      containers:
      - image: quay.io/central/gitbucket:latest
        imagePullPolicy: IfNotPresent
        name: gitbucket
        env:
          - name: gitbucket.db.password
            valueFrom:
              secretKeyRef:
                name: gitbucket-db
                key: gitbucket.db.password
          - name: gitbucket.db.user
            valueFrom:
              secretKeyRef:
                name: gitbucket-db
                key: gitbucket.db.user
          - name: gitbucket.db.db
            valueFrom:
              secretKeyRef:
                name: gitbucket-db
                key: gitbucket.db.url
          - name: GITBUCKET_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: gitbucket-config
                key: gitbucket.base_url
          - name: GITBUCKET_HOME
            valueFrom:
              configMapKeyRef:
                name: gitbucket-config
                key: gitbucket.home
        ports:
        - containerPort: 29418
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/gitbucket
          name: gitbucket-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: gitbucket
      serviceAccountName: gitbucket
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gitbucket-data
          persistentVolumeClaim:
            claimName: gitbucket-data
