kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    app: gitbucket
  name: gitbucket
spec:
  tags:
    - name: "4.38.4"
      from:
        kind: DockerImage
        name: quay.io/gitbucket/gitbucket:4.38.4
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source