apiVersion: batch/v1
kind: Job
metadata:
  name: import-repos-job
spec:
  selector: {}
  template:
    metadata:
      name: import-repos
    spec:
      containers:
      - name: import-repos
        image: image-registry.openshift-image-registry.svc:5000/gitbucket/import-repos:latest
        env:
          - name: import_repos
            valueFrom:
              configMapKeyRef:
                name: gitbucket-config
                key: import_repos
          - name: gitbucket_password
            valueFrom:
              secretKeyRef:
                name: gitbucket-app
                key: gitbucket_password
          - name: gitbucket_user
            valueFrom:
              secretKeyRef:
                name: gitbucket-app
                key: gitbucket_user
          - name: gitbucket_url
            valueFrom:
              secretKeyRef:
                name: gitbucket-app
                key: gitbucket_url
      restartPolicy: Never
