apiVersion: batch/v1
kind: Job
metadata:
  name: import-repos-job
spec:
  selector: {}
  template:
    metadata:
      name: import-repos
    spec:
      containers:
      - name: import-repos
        image: image-registry.openshift-image-registry.svc:5000/gitbucket/import-repos:latest
        env:
          - name: import_repos
            valueFrom:
              configMapKeyRef:
                name: gitbucket-config
                key: import_repos
      restartPolicy: Never
