kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gitbucket
  labels:
    app: gitbucket
    app.kubernetes.io/component: gitbucket
    app.kubernetes.io/instance: gitbucket
spec:
  host: gitbucket.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com
  to:
    kind: Service
    name: gitbucket
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None