kind: Secret
apiVersion: v1
metadata:
  name: gitbucket-db
data:
  gitbucket.db.password: MzQwMTIzOTByMTI0MzIzJCNAJA==
  gitbucket.db.user: Z2l0YnVja2V0
stringData:
  gitbucket.db.url: jdbc:h2:/data/gitbucket/fred;AUTO_SERVER=TRUE;
type: Opaque
