kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-gitops

resources:
  - ../base

patches:
- target:
    kind: OAuth
    name: cluster
  patch: |-
    - op: add
      path: /spec/identityProviders/0/openID/issuer
      value: https://keycloak-sso.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com/auth/realms/openshift