apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
  name: elasticsearch-operator
  namespace: openshift-operators-redhat
spec:
  targetNamespaces:
    - openshift-logging
