apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - common-tools-admins-group.yaml

patchesJson6902:
  - target:
      group: user.openshift.io
      version: v1
      kind: Group
      name: common-tools-admins
    path: common-tools-admins-users.yaml