apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gameoflife-developers-group.yaml

patchesJson6902:
  - target:
      group: user.openshift.io
      version: v1
      kind: Group
      name: gameoflife-developers
    path: gameoflife-developers-users.yaml