apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  labels:
    app: sso
  name: derek-user
spec:
  realmSelector:
    matchLabels:
      app: openshift
  user:
    email: dshirley@redhat.com
    credentials:
      - type: password
        value: p
    emailVerified: true
    enabled: true
    firstName: Derek
    lastName: Shirley
    realmRoles:
    - realm-management
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
    username: derek
