apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - petclinic-developers-group.yaml

patchesJson6902:
  - target:
      group: user.openshift.io
      version: v1
      kind: Group
      name: petclinic-developers
    path: petclinic-developers-users.yaml