apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd-wchfk
      mappingMethod: claim
      name: htpasswd
      type: HTPasswd
    - name: rhsso
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: openshift
        clientSecret: 
          name: openid-client-secret
        ca: 
          name: openidcacrt
        extraScopes: 
        - email
        - profile
        - openid
        extraAuthorizeParameters: 
          include_granted_scopes: "true"
        claims:
          preferredUsername: 
          - preferred_username
          - email
          name: 
          - nickname
          - given_name
          - name
          email: 
          - custom_email_claim
          - email
        issuer: https://keycloak-sso.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com/auth/realms/openshift