apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contoso-cicd

bases:
  - ../base/rbac/users

resources:
  - namespace.yaml
  - quay-creds-secret-sealedsecret.json
  - github-creds-secret-sealedsecret.json