apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Contoso CI/CD
    openshift.io/display-name: Contoso CI/CD
  labels:
    argocd.argoproj.io/managed-by: developer-gitops
  name: contoso-cicd