apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - contoso-developers-group.yaml

patchesJson6902:
  - target:
      group: user.openshift.io
      version: v1
      kind: Group
      name: contoso-developers
    path: contoso-developers-users.yaml