apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

bases:
  - https://github.com/pittar/gitops-catalog/advanced-cluster-security-operator/instance/overlays/internal-registry-integration?ref=acs-operator-refactor