apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

bases:
  - https://github.com/pittar/gitops-catalog/compliance-operator-refactor/advanced-cluster-security-operator/operator/overlays/latest?ref=acs-operator-refactor
