apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

bases:
  - https://github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/operator/overlays/latest?ref=v0.7
