apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-compliance

bases:
  - https://github.com/pittar/gitops-catalog/compliance-operator-refactor/compliance-operator/operator/overlays/release-0.1?ref=compliance-operator-refactor
  - https://github.com/pittar/gitops-catalog/compliance-operator-refactor/compliance-operator/instance/overlays/ocp-cis?ref=compliance-operator-refactor
