apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-compliance

bases:
  - https://github.com/redhat-cop/gitops-catalog/compliance-operator/operator/overlays/release-0.1?ref=v0.6
  - https://github.com/redhat-cop/gitops-catalog/compliance-operator/instance/overlays/ocp-cis?ref=v0.6
