apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-compliance

bases:
  - https://github.com/pittar/gitops-catalog/compliance-operator/operator/overlays/release-0.1?ref=refactor-compliance-operator
  - https://github.com/pittar/gitops-catalog/compliance-operator/instance/overlays/ocp-cis?ref=refactor-compliance-operator
