apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    kubernetes.io/metadata.name: openshift-logging
    argocd.argoproj.io/managed-by: openshift-gitops
  name: openshift-logging
