kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-logging

resources:
  - logging-operator.yaml
  - elasticsearch-operator.yaml
  - logging-instance.yaml
  - elasticsearch-instance.yaml