kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases: 
  - 01-cluster-config
  - 02-cluster-services
  - 03-tenants
  - ../../05-developer-tenants

patches:
- target:
    kind: Application
    name: oauth
  patch: |-
    - op: add
      path: /spec/source/path
      value: 02-cluster-config/06-oauth/nonprod
- target:
    kind: Application
    name: rhsso-operator-instance
  patch: |-
    - op: add
      path: /spec/source/path
      value: 03-cluster-services/05-single-sign-on/instance/nonprod