apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "2"

resources:
  - binary-s2i-task.yaml
  - rox-image-check-task.yaml
  - rox-image-scan-task.yaml
