apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: stackrox-token-secret-pipeline
  namespace: stackrox
spec:
  params:
    - name: NAMESPACE
      type: string
      description: Namespace that needs a StackRox token secret.
  tasks:
    - name: create-api-token-secret
      params:
        - name: NAMESPACE
          value: $(params.NAMESPACE)
        - name: VERSION
          value: latest
      taskRef:
        kind: Task
        name: create-api-token-secret