kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: thin
  volumeMode: Filesystem
