kind: ConfigMap
apiVersion: v1
metadata:
  name: gogs-config
  labels:
    app: gogs
data:
  app.ini: |
    RUN_MODE = prod
    RUN_USER = gogs

    [database]
    DB_TYPE  = postgres
    HOST     = gogs-postgresql:5432
    NAME     = gogs-db
    USER     = gogs-user
    PASSWD   = gogs-user-password

    [repository]
    ROOT = /opt/gogs/data/repositories

    [server]
    ROOT_URL=https://gogs.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com
    SSH_DOMAIN=gogs.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com

    [security]
    INSTALL_LOCK = true

    [service]
    ENABLE_CAPTCHA = false

    [webhook]
    SKIP_TLS_VERIFY = true