kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    app: gitbucket
  name: gitbucket
spec:
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: quay.io/central/gitbucket
      from:
        kind: DockerImage
        name: quay.io/central/gitbucket
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source