apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gogs

bases:
  - serviceAccount.yaml
  - services.yaml
  - routes.yaml
  - pvcs.yaml
  - configMaps.yaml
  - deploymentConfigs.yaml