kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitbucket-data
  labels:
    app: gitbucket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gogs-postgres-data
  labels:
    app: gogs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi