kind: Route
apiVersion: v1
metadata:
  annotations:
    description: Route for application's http service.
  labels:
    app: gogs
  name: gogs
spec:
  host: gogs.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com
  to:
    kind: Service
    name: gogs
    weight: 100
  port:
    targetPort: 3000-tcp
  tls:
    termination: edge
  wildcardPolicy: None