kind: Route
apiVersion: v1
metadata:
  annotations:
    description: Route for application's http service.
  labels:
    app: gogs
  name: gogs
spec:
  host: gogs.apps.dshirley1ipi.vmware.tamlab.rdu2.redhat.com
  to:
    name: gogs