
kind: Service
apiVersion: v1
metadata:
  annotations:
    description: Exposes the database server
  name: gogs-postgresql
  labels:
    app: gogs
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  selector:
    name: gogs-postgresql