kind: Service
apiVersion: v1
metadata:
  name: gitbucket
  labels:
    app: gitbucket
    app.kubernetes.io/component: gitbucket
    app.kubernetes.io/instance: gitbucket
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 29418-tcp
      protocol: TCP
      port: 29418
      targetPort: 29418
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: gitbucket
