kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-gitops

bases:
  - ../../../03-cluster-services/01-sealed-secrets
 # - ../../../services/02-developer-argocd
  - ../../../03-cluster-services/03-openshift-pipelines

resources:
  - cluster-services-project.yaml
